### ISSUE TITLE
Cannot create windows machines

### ISSUE THREAD

**Issue by zackyaz** [test-kitchen/kitchen-openstack#172]
Hi

Instance create stuck on Waiting for server to be ready... (wait_for_server)
looks like wait_for_server doesn't retrieve password of `Administrator` unlike the EC2 version of Kitchen.

Thanks and regards Zacky

**Comment by jjasghar** [comment]
There are a lot of factors here. I'm going to close this due to lack of information, but please reopen this if you can give an accurate description of what's going on.

Just to start, what version of OpenStack, what is your `.kitchen.yml` (scrubbed) look like? Do Linux machines work as expected? Do you have specific issues with using `nova` to create machines? 

The more information you can give us, the more we can help debug. Please Reopen this with the relevant information.
