### ISSUE TITLE
create command will makes duplicated images.

### ISSUE THREAD

**Issue by fortable1999** [test-kitchen/kitchen-openstack#67]
if I run kitchen create command twice,
it will create two instance in openstack with same name.
but it won't happen in kitchen-docker plugin.

Do you think it's better add a checking before create a instance, to make sure
there is always only one instance?

**Comment by icberg7** [comment]
I've experienced the same issue. The OpenStack images in our infrastructure have expired passwords for cloud-user, so you have to log in and change the password before you can actually use the instance.
Unfortunately, because Kitchen doesn't get to the point of setting the state to `Created`, and doesn't check if an image already exists, it spins up another instance. A user could easily do this 3-4 times and not realize that they've spun up multiple instances, which can lead to a problem very quickly.

**Comment by jjasghar** [comment]
We should put in a check at the create command to make sure that we already don't repeat the name. Shouldnt be too hard to create that check.

**Comment by dpetzel** [comment]
I've confirmed this behavior as well. Should have a PR ready shortly.
