### ISSUE TITLE
Connections to Rackspace require the password instead of the API key

### ISSUE THREAD

**Issue by ryanl-ee** [test-kitchen/kitchen-openstack#90]
I've been trying to figure this out on my own but am not knowledgeable enough. I can connect to Rackspace using the config below. The issue of course is that it's asking for the API key but only accepting the password.

    driver:
      name: openstack
      openstack_username: <username>
      openstack_tenant: <tenantid>
      openstack_api_key: "<password>"
      #openstack_api_key: <apikey>
      openstack_auth_url: https://identity.api.rackspacecloud.com/v2.0/tokens
      require_chef_omnibus: true
      image_ref: <image>
      flavor_ref: <flavor>

If I comment the password line and uncomment the apikey line, kitchen create gives me this:

    >>>>>> ------Exception-------
    >>>>>> Class: Kitchen::ActionFailed
    >>>>>> Message: Expected([200, 204]) <=> Actual(401 Unauthorized)
    excon.error.response
      :body          => "{\"unauthorized\":{\"code\":401,\"message\":\"Unable to authenticate user with credentials provided.\"}}"

Does anyone know why this might be? I can reproduce this by creating a new repo, setting up the Gemfile/.kitchen.yml as described in the readme, and running kitchen create. I tried kitchen-rackspace which does take the API key (I'm using kitchen-openstack as there is a tk1.4 branch that supports Windows and WinRM). I checked the Fog code since there are different libs for generic Openstack and Rackspace, but I don't know if or what they do differently that could be requiring the password. instead.

Is this expected behavior?

Thanks for taking the time to read this!

**Comment by jjasghar** [comment]
I havent read completely yet, i'm actaully at the OpenStack Operators meetup getting more Action Items. I'll take a look at this asap, and respond back with suggestions/feedback.

**Comment by RoboticCheese** [comment]
It's been a while since I looked into this but, IIRC, this is because Rackspace doesn't quite run vanilla OpenStack and they have some customized pieces, especially around authentication.

This results in the Rackspace API and the OpenStack API that Rackspace hosts behaving slightly differently (and needing, for example, separate Fog libraries). The "API key" you get from Rackspace only works with the Rackspace-proper API. As you've discovered, though, their OpenStack API will recognize your Rackspace "password" as an OpenStack API key.

It's possible things have changed, but I was never able to find a workaround. It was just a weird Rackspace thing.

**Comment by jjasghar** [comment]
This might be more relevant over here: https://github.com/test-kitchen/kitchen-rackspace, please reopen if you think it should be here.
